version: "3.8"
services:
  db:
    build: ../pipeline/postgres
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=${OCAML_BENCH_DB_PASSWORD?required}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always
    expose: ["5432"]
    cpuset: "${OCAML_BENCH_PLATFORM_CPUSET}"
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    ports:
      - "${OCAML_BENCH_GRAPHQL_PORT?required}:${OCAML_BENCH_GRAPHQL_PORT?required}"
    depends_on:
      db:
        condition: service_healthy
      db-migrate:
        condition: service_started
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://docker:docker@db:5432/docker
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: ${OCAML_BENCH_GRAPHQL_KEY?required}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
    volumes:
      - ../hasura-server/metadata:/hasura-metadata
    cpuset: "${OCAML_BENCH_PLATFORM_CPUSET}"
  frontend:
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
      target: dev
    environment:
      VITE_OCAML_BENCH_PIPELINE_URL: ${OCAML_BENCH_PIPELINE_URL?required}
      VITE_OCAML_BENCH_GRAPHQL_URL: ${OCAML_BENCH_GRAPHQL_URL?required}
      HASURA_GRAPHQL_ADMIN_SECRET: ${OCAML_BENCH_GRAPHQL_KEY?required}
    volumes:
      # We want the src changes made in host to reflect in the container. The
      # container, so that we can use hot-reloading, etc. The container can
      # also make changes like installing node_modules, etc. So, we use
      # consistent/default mode instead of cached or delegated modes.
      - ../frontend:/app/:consistent
    command: ["./scripts/dev.sh"]
    ports:
      [
        "${OCAML_BENCH_FRONTEND_PORT?required}:${OCAML_BENCH_FRONTEND_PORT?required}",
      ]

    restart: always
    depends_on:
      - "graphql-engine"
    cpuset: "${OCAML_BENCH_PLATFORM_CPUSET}"
  pipeline:
    build:
      context: ../pipeline
      dockerfile: ./Dockerfile.dev
      args:
        TARGET_ARCH: ${OCAML_BENCH_TARGET_ARCH?required}
    volumes:
      # Mount the source code of the test project to allow local testing.
      - current-bench-data:/app/current-bench-data
      - ../local-test-repo:/app/local-test-repo
      - /var/run/docker.sock:/var/run/docker.sock
      - ../pipeline/db/migrations:/app/db/migrations
      - ../pipeline:/mnt/project
    ports: ["${OCAML_BENCH_PIPELINE_PORT?required}:${OCAML_BENCH_PIPELINE_PORT?required}"]
    command:
      - "/mnt/project/reload.sh"
      - "/app/bin/current-bench-pipeline"
      - "local"
      - "/app/local-test-repo"
      - "--verbose"
      - "--port=${OCAML_BENCH_PIPELINE_PORT?required}"
      - "--docker-cpu=${OCAML_BENCH_DOCKER_CPU?required}"
      - "--multicore-repositories=${OCAML_BENCH_MULTICORE_REPOSITORIES}"
      - "--conn-info=host=db user=docker port=5432 dbname=docker password=${OCAML_BENCH_DB_PASSWORD?required}"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      OCAML_BENCH_FRONTEND_URL: ${OCAML_BENCH_FRONTEND_URL?required}
  # Apply database migrations. To be used only in development!
  db-migrate:
    image: current-bench_pipeline:latest
    command:
      - "omigrate"
      - "setup"
      - "--verbose"
      - "--source=/app/db/migrations"
      - "--database=postgresql://docker:${OCAML_BENCH_DB_PASSWORD?required}@db:5432/docker"
    depends_on:
      db:
        condition: service_healthy
    cpuset: "${OCAML_BENCH_PLATFORM_CPUSET}"

volumes:
  current-bench-data:
    external: true
